version: '3'

services:
  database:
    image: mongo:7
    container_name: mongoDB
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_DATABASE: nest-pokemon